name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Gerar Snake
        uses: Platane/snk@v3
        with:
          github_user_name: vRodrigues22
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit e push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "gerando snake.svg"
          add: "dist/github-contribution-grid-snake.svg"

      - name: Deploy para o GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
